// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: client_messages.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from client_messages.proto</summary>
public static partial class ClientMessagesReflection {

  #region Descriptor
  /// <summary>File descriptor for client_messages.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static ClientMessagesReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "ChVjbGllbnRfbWVzc2FnZXMucHJvdG8aDG1vZGVscy5wcm90byK9AQoNQ2xp",
          "ZW50TWVzc2FnZRIgCgR0eXBlGBYgAigOMhIuQ2xpZW50TWVzc2FnZVR5cGUS",
          "MwoVcmVnaXN0ZXJfdXNlcl9yZXF1ZXN0GAIgASgLMhQuUmVnaXN0ZXJVc2Vy",
          "UmVxdWVzdBItChJsb2dpbl91c2VyX3JlcXVlc3QYAyABKAsyES5Mb2dpblVz",
          "ZXJSZXF1ZXN0EiYKDmF0dGFja19yZXF1ZXN0GAQgASgLMg4uQXR0YWNrUmVx",
          "dWVzdCK2AQoTUmVnaXN0ZXJVc2VyUmVxdWVzdBIRCgl1c2VyX25hbWUYASAC",
          "KAkSFwoPaGFzaGVkX3Bhc3N3b3JkGAIgAigJEhIKCmZpcnN0X25hbWUYAyAC",
          "KAkSEQoJbGFzdF9uYW1lGAQgAigJEhEKCWF2YXRhcl9pZBgFIAIoCRIRCglk",
          "ZXZpY2VfaWQYBiACKAkSEwoLZGV2aWNlX3R5cGUYByACKAUSEQoJZ29vZ2xl",
          "X2lkGAggAigJIj4KEExvZ2luVXNlclJlcXVlc3QSEQoJdXNlcl9uYW1lGAEg",
          "AigJEhcKD2hhc2hlZF9wYXNzd29yZBgCIAIoCSIyCg1BdHRhY2tSZXF1ZXN0",
          "Eg4KBmRhbWFnZRgBIAIoBRIRCgl0YXJnZXRfaWQYAiACKAkqWgoRQ2xpZW50",
          "TWVzc2FnZVR5cGUSGQoVUkVHSVNURVJfVVNFUl9SRVFVRVNUEAISFgoSTE9H",
          "SU5fVVNFUl9SRVFVRVNUEAMSEgoOQVRUQUNLX1JFUVVFU1QQBA=="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { global::ModelsReflection.Descriptor, },
        new pbr::GeneratedClrTypeInfo(new[] {typeof(global::ClientMessageType), }, null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::ClientMessage), global::ClientMessage.Parser, new[]{ "Type", "RegisterUserRequest", "LoginUserRequest", "AttackRequest" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::RegisterUserRequest), global::RegisterUserRequest.Parser, new[]{ "UserName", "HashedPassword", "FirstName", "LastName", "AvatarId", "DeviceId", "DeviceType", "GoogleId" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::LoginUserRequest), global::LoginUserRequest.Parser, new[]{ "UserName", "HashedPassword" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::AttackRequest), global::AttackRequest.Parser, new[]{ "Damage", "TargetId" }, null, null, null, null)
        }));
  }
  #endregion

}
#region Enums
public enum ClientMessageType {
  [pbr::OriginalName("REGISTER_USER_REQUEST")] RegisterUserRequest = 2,
  [pbr::OriginalName("LOGIN_USER_REQUEST")] LoginUserRequest = 3,
  [pbr::OriginalName("ATTACK_REQUEST")] AttackRequest = 4,
}

#endregion

#region Messages
[global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
public sealed partial class ClientMessage : pb::IMessage<ClientMessage>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<ClientMessage> _parser = new pb::MessageParser<ClientMessage>(() => new ClientMessage());
  private pb::UnknownFieldSet _unknownFields;
  private int _hasBits0;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<ClientMessage> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::ClientMessagesReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public ClientMessage() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public ClientMessage(ClientMessage other) : this() {
    _hasBits0 = other._hasBits0;
    type_ = other.type_;
    registerUserRequest_ = other.registerUserRequest_ != null ? other.registerUserRequest_.Clone() : null;
    loginUserRequest_ = other.loginUserRequest_ != null ? other.loginUserRequest_.Clone() : null;
    attackRequest_ = other.attackRequest_ != null ? other.attackRequest_.Clone() : null;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public ClientMessage Clone() {
    return new ClientMessage(this);
  }

  /// <summary>Field number for the "type" field.</summary>
  public const int TypeFieldNumber = 22;
  private readonly static global::ClientMessageType TypeDefaultValue = global::ClientMessageType.RegisterUserRequest;

  private global::ClientMessageType type_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::ClientMessageType Type {
    get { if ((_hasBits0 & 1) != 0) { return type_; } else { return TypeDefaultValue; } }
    set {
      _hasBits0 |= 1;
      type_ = value;
    }
  }
  /// <summary>Gets whether the "type" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool HasType {
    get { return (_hasBits0 & 1) != 0; }
  }
  /// <summary>Clears the value of the "type" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void ClearType() {
    _hasBits0 &= ~1;
  }

  /// <summary>Field number for the "register_user_request" field.</summary>
  public const int RegisterUserRequestFieldNumber = 2;
  private global::RegisterUserRequest registerUserRequest_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::RegisterUserRequest RegisterUserRequest {
    get { return registerUserRequest_; }
    set {
      registerUserRequest_ = value;
    }
  }

  /// <summary>Field number for the "login_user_request" field.</summary>
  public const int LoginUserRequestFieldNumber = 3;
  private global::LoginUserRequest loginUserRequest_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::LoginUserRequest LoginUserRequest {
    get { return loginUserRequest_; }
    set {
      loginUserRequest_ = value;
    }
  }

  /// <summary>Field number for the "attack_request" field.</summary>
  public const int AttackRequestFieldNumber = 4;
  private global::AttackRequest attackRequest_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::AttackRequest AttackRequest {
    get { return attackRequest_; }
    set {
      attackRequest_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as ClientMessage);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(ClientMessage other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Type != other.Type) return false;
    if (!object.Equals(RegisterUserRequest, other.RegisterUserRequest)) return false;
    if (!object.Equals(LoginUserRequest, other.LoginUserRequest)) return false;
    if (!object.Equals(AttackRequest, other.AttackRequest)) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (HasType) hash ^= Type.GetHashCode();
    if (registerUserRequest_ != null) hash ^= RegisterUserRequest.GetHashCode();
    if (loginUserRequest_ != null) hash ^= LoginUserRequest.GetHashCode();
    if (attackRequest_ != null) hash ^= AttackRequest.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (registerUserRequest_ != null) {
      output.WriteRawTag(18);
      output.WriteMessage(RegisterUserRequest);
    }
    if (loginUserRequest_ != null) {
      output.WriteRawTag(26);
      output.WriteMessage(LoginUserRequest);
    }
    if (attackRequest_ != null) {
      output.WriteRawTag(34);
      output.WriteMessage(AttackRequest);
    }
    if (HasType) {
      output.WriteRawTag(176, 1);
      output.WriteEnum((int) Type);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (registerUserRequest_ != null) {
      output.WriteRawTag(18);
      output.WriteMessage(RegisterUserRequest);
    }
    if (loginUserRequest_ != null) {
      output.WriteRawTag(26);
      output.WriteMessage(LoginUserRequest);
    }
    if (attackRequest_ != null) {
      output.WriteRawTag(34);
      output.WriteMessage(AttackRequest);
    }
    if (HasType) {
      output.WriteRawTag(176, 1);
      output.WriteEnum((int) Type);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (HasType) {
      size += 2 + pb::CodedOutputStream.ComputeEnumSize((int) Type);
    }
    if (registerUserRequest_ != null) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(RegisterUserRequest);
    }
    if (loginUserRequest_ != null) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(LoginUserRequest);
    }
    if (attackRequest_ != null) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(AttackRequest);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(ClientMessage other) {
    if (other == null) {
      return;
    }
    if (other.HasType) {
      Type = other.Type;
    }
    if (other.registerUserRequest_ != null) {
      if (registerUserRequest_ == null) {
        RegisterUserRequest = new global::RegisterUserRequest();
      }
      RegisterUserRequest.MergeFrom(other.RegisterUserRequest);
    }
    if (other.loginUserRequest_ != null) {
      if (loginUserRequest_ == null) {
        LoginUserRequest = new global::LoginUserRequest();
      }
      LoginUserRequest.MergeFrom(other.LoginUserRequest);
    }
    if (other.attackRequest_ != null) {
      if (attackRequest_ == null) {
        AttackRequest = new global::AttackRequest();
      }
      AttackRequest.MergeFrom(other.AttackRequest);
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 18: {
          if (registerUserRequest_ == null) {
            RegisterUserRequest = new global::RegisterUserRequest();
          }
          input.ReadMessage(RegisterUserRequest);
          break;
        }
        case 26: {
          if (loginUserRequest_ == null) {
            LoginUserRequest = new global::LoginUserRequest();
          }
          input.ReadMessage(LoginUserRequest);
          break;
        }
        case 34: {
          if (attackRequest_ == null) {
            AttackRequest = new global::AttackRequest();
          }
          input.ReadMessage(AttackRequest);
          break;
        }
        case 176: {
          Type = (global::ClientMessageType) input.ReadEnum();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 18: {
          if (registerUserRequest_ == null) {
            RegisterUserRequest = new global::RegisterUserRequest();
          }
          input.ReadMessage(RegisterUserRequest);
          break;
        }
        case 26: {
          if (loginUserRequest_ == null) {
            LoginUserRequest = new global::LoginUserRequest();
          }
          input.ReadMessage(LoginUserRequest);
          break;
        }
        case 34: {
          if (attackRequest_ == null) {
            AttackRequest = new global::AttackRequest();
          }
          input.ReadMessage(AttackRequest);
          break;
        }
        case 176: {
          Type = (global::ClientMessageType) input.ReadEnum();
          break;
        }
      }
    }
  }
  #endif

}

[global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
public sealed partial class RegisterUserRequest : pb::IMessage<RegisterUserRequest>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<RegisterUserRequest> _parser = new pb::MessageParser<RegisterUserRequest>(() => new RegisterUserRequest());
  private pb::UnknownFieldSet _unknownFields;
  private int _hasBits0;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<RegisterUserRequest> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::ClientMessagesReflection.Descriptor.MessageTypes[1]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public RegisterUserRequest() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public RegisterUserRequest(RegisterUserRequest other) : this() {
    _hasBits0 = other._hasBits0;
    userName_ = other.userName_;
    hashedPassword_ = other.hashedPassword_;
    firstName_ = other.firstName_;
    lastName_ = other.lastName_;
    avatarId_ = other.avatarId_;
    deviceId_ = other.deviceId_;
    deviceType_ = other.deviceType_;
    googleId_ = other.googleId_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public RegisterUserRequest Clone() {
    return new RegisterUserRequest(this);
  }

  /// <summary>Field number for the "user_name" field.</summary>
  public const int UserNameFieldNumber = 1;
  private readonly static string UserNameDefaultValue = "";

  private string userName_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string UserName {
    get { return userName_ ?? UserNameDefaultValue; }
    set {
      userName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }
  /// <summary>Gets whether the "user_name" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool HasUserName {
    get { return userName_ != null; }
  }
  /// <summary>Clears the value of the "user_name" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void ClearUserName() {
    userName_ = null;
  }

  /// <summary>Field number for the "hashed_password" field.</summary>
  public const int HashedPasswordFieldNumber = 2;
  private readonly static string HashedPasswordDefaultValue = "";

  private string hashedPassword_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string HashedPassword {
    get { return hashedPassword_ ?? HashedPasswordDefaultValue; }
    set {
      hashedPassword_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }
  /// <summary>Gets whether the "hashed_password" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool HasHashedPassword {
    get { return hashedPassword_ != null; }
  }
  /// <summary>Clears the value of the "hashed_password" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void ClearHashedPassword() {
    hashedPassword_ = null;
  }

  /// <summary>Field number for the "first_name" field.</summary>
  public const int FirstNameFieldNumber = 3;
  private readonly static string FirstNameDefaultValue = "";

  private string firstName_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string FirstName {
    get { return firstName_ ?? FirstNameDefaultValue; }
    set {
      firstName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }
  /// <summary>Gets whether the "first_name" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool HasFirstName {
    get { return firstName_ != null; }
  }
  /// <summary>Clears the value of the "first_name" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void ClearFirstName() {
    firstName_ = null;
  }

  /// <summary>Field number for the "last_name" field.</summary>
  public const int LastNameFieldNumber = 4;
  private readonly static string LastNameDefaultValue = "";

  private string lastName_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string LastName {
    get { return lastName_ ?? LastNameDefaultValue; }
    set {
      lastName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }
  /// <summary>Gets whether the "last_name" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool HasLastName {
    get { return lastName_ != null; }
  }
  /// <summary>Clears the value of the "last_name" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void ClearLastName() {
    lastName_ = null;
  }

  /// <summary>Field number for the "avatar_id" field.</summary>
  public const int AvatarIdFieldNumber = 5;
  private readonly static string AvatarIdDefaultValue = "";

  private string avatarId_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string AvatarId {
    get { return avatarId_ ?? AvatarIdDefaultValue; }
    set {
      avatarId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }
  /// <summary>Gets whether the "avatar_id" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool HasAvatarId {
    get { return avatarId_ != null; }
  }
  /// <summary>Clears the value of the "avatar_id" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void ClearAvatarId() {
    avatarId_ = null;
  }

  /// <summary>Field number for the "device_id" field.</summary>
  public const int DeviceIdFieldNumber = 6;
  private readonly static string DeviceIdDefaultValue = "";

  private string deviceId_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string DeviceId {
    get { return deviceId_ ?? DeviceIdDefaultValue; }
    set {
      deviceId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }
  /// <summary>Gets whether the "device_id" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool HasDeviceId {
    get { return deviceId_ != null; }
  }
  /// <summary>Clears the value of the "device_id" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void ClearDeviceId() {
    deviceId_ = null;
  }

  /// <summary>Field number for the "device_type" field.</summary>
  public const int DeviceTypeFieldNumber = 7;
  private readonly static int DeviceTypeDefaultValue = 0;

  private int deviceType_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int DeviceType {
    get { if ((_hasBits0 & 1) != 0) { return deviceType_; } else { return DeviceTypeDefaultValue; } }
    set {
      _hasBits0 |= 1;
      deviceType_ = value;
    }
  }
  /// <summary>Gets whether the "device_type" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool HasDeviceType {
    get { return (_hasBits0 & 1) != 0; }
  }
  /// <summary>Clears the value of the "device_type" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void ClearDeviceType() {
    _hasBits0 &= ~1;
  }

  /// <summary>Field number for the "google_id" field.</summary>
  public const int GoogleIdFieldNumber = 8;
  private readonly static string GoogleIdDefaultValue = "";

  private string googleId_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string GoogleId {
    get { return googleId_ ?? GoogleIdDefaultValue; }
    set {
      googleId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }
  /// <summary>Gets whether the "google_id" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool HasGoogleId {
    get { return googleId_ != null; }
  }
  /// <summary>Clears the value of the "google_id" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void ClearGoogleId() {
    googleId_ = null;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as RegisterUserRequest);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(RegisterUserRequest other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (UserName != other.UserName) return false;
    if (HashedPassword != other.HashedPassword) return false;
    if (FirstName != other.FirstName) return false;
    if (LastName != other.LastName) return false;
    if (AvatarId != other.AvatarId) return false;
    if (DeviceId != other.DeviceId) return false;
    if (DeviceType != other.DeviceType) return false;
    if (GoogleId != other.GoogleId) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (HasUserName) hash ^= UserName.GetHashCode();
    if (HasHashedPassword) hash ^= HashedPassword.GetHashCode();
    if (HasFirstName) hash ^= FirstName.GetHashCode();
    if (HasLastName) hash ^= LastName.GetHashCode();
    if (HasAvatarId) hash ^= AvatarId.GetHashCode();
    if (HasDeviceId) hash ^= DeviceId.GetHashCode();
    if (HasDeviceType) hash ^= DeviceType.GetHashCode();
    if (HasGoogleId) hash ^= GoogleId.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (HasUserName) {
      output.WriteRawTag(10);
      output.WriteString(UserName);
    }
    if (HasHashedPassword) {
      output.WriteRawTag(18);
      output.WriteString(HashedPassword);
    }
    if (HasFirstName) {
      output.WriteRawTag(26);
      output.WriteString(FirstName);
    }
    if (HasLastName) {
      output.WriteRawTag(34);
      output.WriteString(LastName);
    }
    if (HasAvatarId) {
      output.WriteRawTag(42);
      output.WriteString(AvatarId);
    }
    if (HasDeviceId) {
      output.WriteRawTag(50);
      output.WriteString(DeviceId);
    }
    if (HasDeviceType) {
      output.WriteRawTag(56);
      output.WriteInt32(DeviceType);
    }
    if (HasGoogleId) {
      output.WriteRawTag(66);
      output.WriteString(GoogleId);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (HasUserName) {
      output.WriteRawTag(10);
      output.WriteString(UserName);
    }
    if (HasHashedPassword) {
      output.WriteRawTag(18);
      output.WriteString(HashedPassword);
    }
    if (HasFirstName) {
      output.WriteRawTag(26);
      output.WriteString(FirstName);
    }
    if (HasLastName) {
      output.WriteRawTag(34);
      output.WriteString(LastName);
    }
    if (HasAvatarId) {
      output.WriteRawTag(42);
      output.WriteString(AvatarId);
    }
    if (HasDeviceId) {
      output.WriteRawTag(50);
      output.WriteString(DeviceId);
    }
    if (HasDeviceType) {
      output.WriteRawTag(56);
      output.WriteInt32(DeviceType);
    }
    if (HasGoogleId) {
      output.WriteRawTag(66);
      output.WriteString(GoogleId);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (HasUserName) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(UserName);
    }
    if (HasHashedPassword) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(HashedPassword);
    }
    if (HasFirstName) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(FirstName);
    }
    if (HasLastName) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(LastName);
    }
    if (HasAvatarId) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(AvatarId);
    }
    if (HasDeviceId) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(DeviceId);
    }
    if (HasDeviceType) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(DeviceType);
    }
    if (HasGoogleId) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(GoogleId);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(RegisterUserRequest other) {
    if (other == null) {
      return;
    }
    if (other.HasUserName) {
      UserName = other.UserName;
    }
    if (other.HasHashedPassword) {
      HashedPassword = other.HashedPassword;
    }
    if (other.HasFirstName) {
      FirstName = other.FirstName;
    }
    if (other.HasLastName) {
      LastName = other.LastName;
    }
    if (other.HasAvatarId) {
      AvatarId = other.AvatarId;
    }
    if (other.HasDeviceId) {
      DeviceId = other.DeviceId;
    }
    if (other.HasDeviceType) {
      DeviceType = other.DeviceType;
    }
    if (other.HasGoogleId) {
      GoogleId = other.GoogleId;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          UserName = input.ReadString();
          break;
        }
        case 18: {
          HashedPassword = input.ReadString();
          break;
        }
        case 26: {
          FirstName = input.ReadString();
          break;
        }
        case 34: {
          LastName = input.ReadString();
          break;
        }
        case 42: {
          AvatarId = input.ReadString();
          break;
        }
        case 50: {
          DeviceId = input.ReadString();
          break;
        }
        case 56: {
          DeviceType = input.ReadInt32();
          break;
        }
        case 66: {
          GoogleId = input.ReadString();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 10: {
          UserName = input.ReadString();
          break;
        }
        case 18: {
          HashedPassword = input.ReadString();
          break;
        }
        case 26: {
          FirstName = input.ReadString();
          break;
        }
        case 34: {
          LastName = input.ReadString();
          break;
        }
        case 42: {
          AvatarId = input.ReadString();
          break;
        }
        case 50: {
          DeviceId = input.ReadString();
          break;
        }
        case 56: {
          DeviceType = input.ReadInt32();
          break;
        }
        case 66: {
          GoogleId = input.ReadString();
          break;
        }
      }
    }
  }
  #endif

}

[global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
public sealed partial class LoginUserRequest : pb::IMessage<LoginUserRequest>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<LoginUserRequest> _parser = new pb::MessageParser<LoginUserRequest>(() => new LoginUserRequest());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<LoginUserRequest> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::ClientMessagesReflection.Descriptor.MessageTypes[2]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public LoginUserRequest() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public LoginUserRequest(LoginUserRequest other) : this() {
    userName_ = other.userName_;
    hashedPassword_ = other.hashedPassword_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public LoginUserRequest Clone() {
    return new LoginUserRequest(this);
  }

  /// <summary>Field number for the "user_name" field.</summary>
  public const int UserNameFieldNumber = 1;
  private readonly static string UserNameDefaultValue = "";

  private string userName_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string UserName {
    get { return userName_ ?? UserNameDefaultValue; }
    set {
      userName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }
  /// <summary>Gets whether the "user_name" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool HasUserName {
    get { return userName_ != null; }
  }
  /// <summary>Clears the value of the "user_name" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void ClearUserName() {
    userName_ = null;
  }

  /// <summary>Field number for the "hashed_password" field.</summary>
  public const int HashedPasswordFieldNumber = 2;
  private readonly static string HashedPasswordDefaultValue = "";

  private string hashedPassword_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string HashedPassword {
    get { return hashedPassword_ ?? HashedPasswordDefaultValue; }
    set {
      hashedPassword_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }
  /// <summary>Gets whether the "hashed_password" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool HasHashedPassword {
    get { return hashedPassword_ != null; }
  }
  /// <summary>Clears the value of the "hashed_password" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void ClearHashedPassword() {
    hashedPassword_ = null;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as LoginUserRequest);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(LoginUserRequest other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (UserName != other.UserName) return false;
    if (HashedPassword != other.HashedPassword) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (HasUserName) hash ^= UserName.GetHashCode();
    if (HasHashedPassword) hash ^= HashedPassword.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (HasUserName) {
      output.WriteRawTag(10);
      output.WriteString(UserName);
    }
    if (HasHashedPassword) {
      output.WriteRawTag(18);
      output.WriteString(HashedPassword);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (HasUserName) {
      output.WriteRawTag(10);
      output.WriteString(UserName);
    }
    if (HasHashedPassword) {
      output.WriteRawTag(18);
      output.WriteString(HashedPassword);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (HasUserName) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(UserName);
    }
    if (HasHashedPassword) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(HashedPassword);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(LoginUserRequest other) {
    if (other == null) {
      return;
    }
    if (other.HasUserName) {
      UserName = other.UserName;
    }
    if (other.HasHashedPassword) {
      HashedPassword = other.HashedPassword;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          UserName = input.ReadString();
          break;
        }
        case 18: {
          HashedPassword = input.ReadString();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 10: {
          UserName = input.ReadString();
          break;
        }
        case 18: {
          HashedPassword = input.ReadString();
          break;
        }
      }
    }
  }
  #endif

}

[global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
public sealed partial class AttackRequest : pb::IMessage<AttackRequest>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<AttackRequest> _parser = new pb::MessageParser<AttackRequest>(() => new AttackRequest());
  private pb::UnknownFieldSet _unknownFields;
  private int _hasBits0;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<AttackRequest> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::ClientMessagesReflection.Descriptor.MessageTypes[3]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public AttackRequest() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public AttackRequest(AttackRequest other) : this() {
    _hasBits0 = other._hasBits0;
    damage_ = other.damage_;
    targetId_ = other.targetId_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public AttackRequest Clone() {
    return new AttackRequest(this);
  }

  /// <summary>Field number for the "damage" field.</summary>
  public const int DamageFieldNumber = 1;
  private readonly static int DamageDefaultValue = 0;

  private int damage_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int Damage {
    get { if ((_hasBits0 & 1) != 0) { return damage_; } else { return DamageDefaultValue; } }
    set {
      _hasBits0 |= 1;
      damage_ = value;
    }
  }
  /// <summary>Gets whether the "damage" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool HasDamage {
    get { return (_hasBits0 & 1) != 0; }
  }
  /// <summary>Clears the value of the "damage" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void ClearDamage() {
    _hasBits0 &= ~1;
  }

  /// <summary>Field number for the "target_id" field.</summary>
  public const int TargetIdFieldNumber = 2;
  private readonly static string TargetIdDefaultValue = "";

  private string targetId_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string TargetId {
    get { return targetId_ ?? TargetIdDefaultValue; }
    set {
      targetId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }
  /// <summary>Gets whether the "target_id" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool HasTargetId {
    get { return targetId_ != null; }
  }
  /// <summary>Clears the value of the "target_id" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void ClearTargetId() {
    targetId_ = null;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as AttackRequest);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(AttackRequest other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Damage != other.Damage) return false;
    if (TargetId != other.TargetId) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (HasDamage) hash ^= Damage.GetHashCode();
    if (HasTargetId) hash ^= TargetId.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (HasDamage) {
      output.WriteRawTag(8);
      output.WriteInt32(Damage);
    }
    if (HasTargetId) {
      output.WriteRawTag(18);
      output.WriteString(TargetId);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (HasDamage) {
      output.WriteRawTag(8);
      output.WriteInt32(Damage);
    }
    if (HasTargetId) {
      output.WriteRawTag(18);
      output.WriteString(TargetId);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (HasDamage) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(Damage);
    }
    if (HasTargetId) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(TargetId);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(AttackRequest other) {
    if (other == null) {
      return;
    }
    if (other.HasDamage) {
      Damage = other.Damage;
    }
    if (other.HasTargetId) {
      TargetId = other.TargetId;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          Damage = input.ReadInt32();
          break;
        }
        case 18: {
          TargetId = input.ReadString();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 8: {
          Damage = input.ReadInt32();
          break;
        }
        case 18: {
          TargetId = input.ReadString();
          break;
        }
      }
    }
  }
  #endif

}

#endregion


#endregion Designer generated code
