// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: server_messages.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from server_messages.proto</summary>
public static partial class ServerMessagesReflection {

  #region Descriptor
  /// <summary>File descriptor for server_messages.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static ServerMessagesReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "ChVzZXJ2ZXJfbWVzc2FnZXMucHJvdG8aDG1vZGVscy5wcm90byLDAQoNU2Vy",
          "dmVyTWVzc2FnZRIgCgR0eXBlGBggASgOMhIuU2VydmVyTWVzc2FnZVR5cGUS",
          "NQoWcmVnaXN0ZXJfdXNlcl9yZXNwb25zZRgBIAEoCzIVLlJlZ2lzdGVyVXNl",
          "clJlc3BvbnNlEi8KE2xvZ2luX3VzZXJfcmVzcG9uc2UYAiABKAsyEi5Mb2dp",
          "blVzZXJSZXNwb25zZRIoCg9hdHRhY2tfcmVzcG9uc2UYAyABKAsyDy5BdHRh",
          "Y2tSZXNwb25zZSJVChRSZWdpc3RlclVzZXJSZXNwb25zZRIYChBtZXRhZGF0",
          "YV92ZXJzaW9uGAEgAigFEhEKCXVzZXJfbmFtZRgCIAEoCRIQCghwYXNzd29y",
          "ZBgDIAEoCSJDChFMb2dpblVzZXJSZXNwb25zZRIYChBtZXRhZGF0YV92ZXJz",
          "aW9uGAEgAigFEhQKDGdhbWVfdmVyc2lvbhgCIAIoBSJWCg5BdHRhY2tSZXNw",
          "b25zZRIRCglwbGF5ZXJfaWQYASACKAkSEQoJdGFyZ2V0X2lkGAIgAigJEh4K",
          "FnRhcmdldF9ocF9hZnRlcl9hdHRhY2sYAyACKAIqXQoRU2VydmVyTWVzc2Fn",
          "ZVR5cGUSGgoWUkVHSVNURVJfVVNFUl9SRVNQT05TRRABEhcKE0xPR0lOX1VT",
          "RVJfUkVTUE9OU0UQAhITCg9BVFRBQ0tfUkVTUE9OU0UQAw=="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { global::ModelsReflection.Descriptor, },
        new pbr::GeneratedClrTypeInfo(new[] {typeof(global::ServerMessageType), }, null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::ServerMessage), global::ServerMessage.Parser, new[]{ "Type", "RegisterUserResponse", "LoginUserResponse", "AttackResponse" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::RegisterUserResponse), global::RegisterUserResponse.Parser, new[]{ "MetadataVersion", "UserName", "Password" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::LoginUserResponse), global::LoginUserResponse.Parser, new[]{ "MetadataVersion", "GameVersion" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::AttackResponse), global::AttackResponse.Parser, new[]{ "PlayerId", "TargetId", "TargetHpAfterAttack" }, null, null, null, null)
        }));
  }
  #endregion

}
#region Enums
public enum ServerMessageType {
  [pbr::OriginalName("REGISTER_USER_RESPONSE")] RegisterUserResponse = 1,
  [pbr::OriginalName("LOGIN_USER_RESPONSE")] LoginUserResponse = 2,
  [pbr::OriginalName("ATTACK_RESPONSE")] AttackResponse = 3,
}

#endregion

#region Messages
[global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
public sealed partial class ServerMessage : pb::IMessage<ServerMessage>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<ServerMessage> _parser = new pb::MessageParser<ServerMessage>(() => new ServerMessage());
  private pb::UnknownFieldSet _unknownFields;
  private int _hasBits0;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<ServerMessage> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::ServerMessagesReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public ServerMessage() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public ServerMessage(ServerMessage other) : this() {
    _hasBits0 = other._hasBits0;
    type_ = other.type_;
    registerUserResponse_ = other.registerUserResponse_ != null ? other.registerUserResponse_.Clone() : null;
    loginUserResponse_ = other.loginUserResponse_ != null ? other.loginUserResponse_.Clone() : null;
    attackResponse_ = other.attackResponse_ != null ? other.attackResponse_.Clone() : null;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public ServerMessage Clone() {
    return new ServerMessage(this);
  }

  /// <summary>Field number for the "type" field.</summary>
  public const int TypeFieldNumber = 24;
  private readonly static global::ServerMessageType TypeDefaultValue = global::ServerMessageType.RegisterUserResponse;

  private global::ServerMessageType type_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::ServerMessageType Type {
    get { if ((_hasBits0 & 1) != 0) { return type_; } else { return TypeDefaultValue; } }
    set {
      _hasBits0 |= 1;
      type_ = value;
    }
  }
  /// <summary>Gets whether the "type" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool HasType {
    get { return (_hasBits0 & 1) != 0; }
  }
  /// <summary>Clears the value of the "type" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void ClearType() {
    _hasBits0 &= ~1;
  }

  /// <summary>Field number for the "register_user_response" field.</summary>
  public const int RegisterUserResponseFieldNumber = 1;
  private global::RegisterUserResponse registerUserResponse_;
  /// <summary>
  ///responses
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::RegisterUserResponse RegisterUserResponse {
    get { return registerUserResponse_; }
    set {
      registerUserResponse_ = value;
    }
  }

  /// <summary>Field number for the "login_user_response" field.</summary>
  public const int LoginUserResponseFieldNumber = 2;
  private global::LoginUserResponse loginUserResponse_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::LoginUserResponse LoginUserResponse {
    get { return loginUserResponse_; }
    set {
      loginUserResponse_ = value;
    }
  }

  /// <summary>Field number for the "attack_response" field.</summary>
  public const int AttackResponseFieldNumber = 3;
  private global::AttackResponse attackResponse_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::AttackResponse AttackResponse {
    get { return attackResponse_; }
    set {
      attackResponse_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as ServerMessage);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(ServerMessage other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Type != other.Type) return false;
    if (!object.Equals(RegisterUserResponse, other.RegisterUserResponse)) return false;
    if (!object.Equals(LoginUserResponse, other.LoginUserResponse)) return false;
    if (!object.Equals(AttackResponse, other.AttackResponse)) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (HasType) hash ^= Type.GetHashCode();
    if (registerUserResponse_ != null) hash ^= RegisterUserResponse.GetHashCode();
    if (loginUserResponse_ != null) hash ^= LoginUserResponse.GetHashCode();
    if (attackResponse_ != null) hash ^= AttackResponse.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (registerUserResponse_ != null) {
      output.WriteRawTag(10);
      output.WriteMessage(RegisterUserResponse);
    }
    if (loginUserResponse_ != null) {
      output.WriteRawTag(18);
      output.WriteMessage(LoginUserResponse);
    }
    if (attackResponse_ != null) {
      output.WriteRawTag(26);
      output.WriteMessage(AttackResponse);
    }
    if (HasType) {
      output.WriteRawTag(192, 1);
      output.WriteEnum((int) Type);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (registerUserResponse_ != null) {
      output.WriteRawTag(10);
      output.WriteMessage(RegisterUserResponse);
    }
    if (loginUserResponse_ != null) {
      output.WriteRawTag(18);
      output.WriteMessage(LoginUserResponse);
    }
    if (attackResponse_ != null) {
      output.WriteRawTag(26);
      output.WriteMessage(AttackResponse);
    }
    if (HasType) {
      output.WriteRawTag(192, 1);
      output.WriteEnum((int) Type);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (HasType) {
      size += 2 + pb::CodedOutputStream.ComputeEnumSize((int) Type);
    }
    if (registerUserResponse_ != null) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(RegisterUserResponse);
    }
    if (loginUserResponse_ != null) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(LoginUserResponse);
    }
    if (attackResponse_ != null) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(AttackResponse);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(ServerMessage other) {
    if (other == null) {
      return;
    }
    if (other.HasType) {
      Type = other.Type;
    }
    if (other.registerUserResponse_ != null) {
      if (registerUserResponse_ == null) {
        RegisterUserResponse = new global::RegisterUserResponse();
      }
      RegisterUserResponse.MergeFrom(other.RegisterUserResponse);
    }
    if (other.loginUserResponse_ != null) {
      if (loginUserResponse_ == null) {
        LoginUserResponse = new global::LoginUserResponse();
      }
      LoginUserResponse.MergeFrom(other.LoginUserResponse);
    }
    if (other.attackResponse_ != null) {
      if (attackResponse_ == null) {
        AttackResponse = new global::AttackResponse();
      }
      AttackResponse.MergeFrom(other.AttackResponse);
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          if (registerUserResponse_ == null) {
            RegisterUserResponse = new global::RegisterUserResponse();
          }
          input.ReadMessage(RegisterUserResponse);
          break;
        }
        case 18: {
          if (loginUserResponse_ == null) {
            LoginUserResponse = new global::LoginUserResponse();
          }
          input.ReadMessage(LoginUserResponse);
          break;
        }
        case 26: {
          if (attackResponse_ == null) {
            AttackResponse = new global::AttackResponse();
          }
          input.ReadMessage(AttackResponse);
          break;
        }
        case 192: {
          Type = (global::ServerMessageType) input.ReadEnum();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 10: {
          if (registerUserResponse_ == null) {
            RegisterUserResponse = new global::RegisterUserResponse();
          }
          input.ReadMessage(RegisterUserResponse);
          break;
        }
        case 18: {
          if (loginUserResponse_ == null) {
            LoginUserResponse = new global::LoginUserResponse();
          }
          input.ReadMessage(LoginUserResponse);
          break;
        }
        case 26: {
          if (attackResponse_ == null) {
            AttackResponse = new global::AttackResponse();
          }
          input.ReadMessage(AttackResponse);
          break;
        }
        case 192: {
          Type = (global::ServerMessageType) input.ReadEnum();
          break;
        }
      }
    }
  }
  #endif

}

[global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
public sealed partial class RegisterUserResponse : pb::IMessage<RegisterUserResponse>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<RegisterUserResponse> _parser = new pb::MessageParser<RegisterUserResponse>(() => new RegisterUserResponse());
  private pb::UnknownFieldSet _unknownFields;
  private int _hasBits0;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<RegisterUserResponse> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::ServerMessagesReflection.Descriptor.MessageTypes[1]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public RegisterUserResponse() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public RegisterUserResponse(RegisterUserResponse other) : this() {
    _hasBits0 = other._hasBits0;
    metadataVersion_ = other.metadataVersion_;
    userName_ = other.userName_;
    password_ = other.password_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public RegisterUserResponse Clone() {
    return new RegisterUserResponse(this);
  }

  /// <summary>Field number for the "metadata_version" field.</summary>
  public const int MetadataVersionFieldNumber = 1;
  private readonly static int MetadataVersionDefaultValue = 0;

  private int metadataVersion_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int MetadataVersion {
    get { if ((_hasBits0 & 1) != 0) { return metadataVersion_; } else { return MetadataVersionDefaultValue; } }
    set {
      _hasBits0 |= 1;
      metadataVersion_ = value;
    }
  }
  /// <summary>Gets whether the "metadata_version" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool HasMetadataVersion {
    get { return (_hasBits0 & 1) != 0; }
  }
  /// <summary>Clears the value of the "metadata_version" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void ClearMetadataVersion() {
    _hasBits0 &= ~1;
  }

  /// <summary>Field number for the "user_name" field.</summary>
  public const int UserNameFieldNumber = 2;
  private readonly static string UserNameDefaultValue = "";

  private string userName_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string UserName {
    get { return userName_ ?? UserNameDefaultValue; }
    set {
      userName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }
  /// <summary>Gets whether the "user_name" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool HasUserName {
    get { return userName_ != null; }
  }
  /// <summary>Clears the value of the "user_name" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void ClearUserName() {
    userName_ = null;
  }

  /// <summary>Field number for the "password" field.</summary>
  public const int PasswordFieldNumber = 3;
  private readonly static string PasswordDefaultValue = "";

  private string password_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string Password {
    get { return password_ ?? PasswordDefaultValue; }
    set {
      password_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }
  /// <summary>Gets whether the "password" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool HasPassword {
    get { return password_ != null; }
  }
  /// <summary>Clears the value of the "password" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void ClearPassword() {
    password_ = null;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as RegisterUserResponse);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(RegisterUserResponse other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (MetadataVersion != other.MetadataVersion) return false;
    if (UserName != other.UserName) return false;
    if (Password != other.Password) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (HasMetadataVersion) hash ^= MetadataVersion.GetHashCode();
    if (HasUserName) hash ^= UserName.GetHashCode();
    if (HasPassword) hash ^= Password.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (HasMetadataVersion) {
      output.WriteRawTag(8);
      output.WriteInt32(MetadataVersion);
    }
    if (HasUserName) {
      output.WriteRawTag(18);
      output.WriteString(UserName);
    }
    if (HasPassword) {
      output.WriteRawTag(26);
      output.WriteString(Password);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (HasMetadataVersion) {
      output.WriteRawTag(8);
      output.WriteInt32(MetadataVersion);
    }
    if (HasUserName) {
      output.WriteRawTag(18);
      output.WriteString(UserName);
    }
    if (HasPassword) {
      output.WriteRawTag(26);
      output.WriteString(Password);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (HasMetadataVersion) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(MetadataVersion);
    }
    if (HasUserName) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(UserName);
    }
    if (HasPassword) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Password);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(RegisterUserResponse other) {
    if (other == null) {
      return;
    }
    if (other.HasMetadataVersion) {
      MetadataVersion = other.MetadataVersion;
    }
    if (other.HasUserName) {
      UserName = other.UserName;
    }
    if (other.HasPassword) {
      Password = other.Password;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          MetadataVersion = input.ReadInt32();
          break;
        }
        case 18: {
          UserName = input.ReadString();
          break;
        }
        case 26: {
          Password = input.ReadString();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 8: {
          MetadataVersion = input.ReadInt32();
          break;
        }
        case 18: {
          UserName = input.ReadString();
          break;
        }
        case 26: {
          Password = input.ReadString();
          break;
        }
      }
    }
  }
  #endif

}

[global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
public sealed partial class LoginUserResponse : pb::IMessage<LoginUserResponse>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<LoginUserResponse> _parser = new pb::MessageParser<LoginUserResponse>(() => new LoginUserResponse());
  private pb::UnknownFieldSet _unknownFields;
  private int _hasBits0;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<LoginUserResponse> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::ServerMessagesReflection.Descriptor.MessageTypes[2]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public LoginUserResponse() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public LoginUserResponse(LoginUserResponse other) : this() {
    _hasBits0 = other._hasBits0;
    metadataVersion_ = other.metadataVersion_;
    gameVersion_ = other.gameVersion_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public LoginUserResponse Clone() {
    return new LoginUserResponse(this);
  }

  /// <summary>Field number for the "metadata_version" field.</summary>
  public const int MetadataVersionFieldNumber = 1;
  private readonly static int MetadataVersionDefaultValue = 0;

  private int metadataVersion_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int MetadataVersion {
    get { if ((_hasBits0 & 1) != 0) { return metadataVersion_; } else { return MetadataVersionDefaultValue; } }
    set {
      _hasBits0 |= 1;
      metadataVersion_ = value;
    }
  }
  /// <summary>Gets whether the "metadata_version" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool HasMetadataVersion {
    get { return (_hasBits0 & 1) != 0; }
  }
  /// <summary>Clears the value of the "metadata_version" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void ClearMetadataVersion() {
    _hasBits0 &= ~1;
  }

  /// <summary>Field number for the "game_version" field.</summary>
  public const int GameVersionFieldNumber = 2;
  private readonly static int GameVersionDefaultValue = 0;

  private int gameVersion_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int GameVersion {
    get { if ((_hasBits0 & 2) != 0) { return gameVersion_; } else { return GameVersionDefaultValue; } }
    set {
      _hasBits0 |= 2;
      gameVersion_ = value;
    }
  }
  /// <summary>Gets whether the "game_version" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool HasGameVersion {
    get { return (_hasBits0 & 2) != 0; }
  }
  /// <summary>Clears the value of the "game_version" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void ClearGameVersion() {
    _hasBits0 &= ~2;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as LoginUserResponse);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(LoginUserResponse other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (MetadataVersion != other.MetadataVersion) return false;
    if (GameVersion != other.GameVersion) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (HasMetadataVersion) hash ^= MetadataVersion.GetHashCode();
    if (HasGameVersion) hash ^= GameVersion.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (HasMetadataVersion) {
      output.WriteRawTag(8);
      output.WriteInt32(MetadataVersion);
    }
    if (HasGameVersion) {
      output.WriteRawTag(16);
      output.WriteInt32(GameVersion);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (HasMetadataVersion) {
      output.WriteRawTag(8);
      output.WriteInt32(MetadataVersion);
    }
    if (HasGameVersion) {
      output.WriteRawTag(16);
      output.WriteInt32(GameVersion);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (HasMetadataVersion) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(MetadataVersion);
    }
    if (HasGameVersion) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(GameVersion);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(LoginUserResponse other) {
    if (other == null) {
      return;
    }
    if (other.HasMetadataVersion) {
      MetadataVersion = other.MetadataVersion;
    }
    if (other.HasGameVersion) {
      GameVersion = other.GameVersion;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          MetadataVersion = input.ReadInt32();
          break;
        }
        case 16: {
          GameVersion = input.ReadInt32();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 8: {
          MetadataVersion = input.ReadInt32();
          break;
        }
        case 16: {
          GameVersion = input.ReadInt32();
          break;
        }
      }
    }
  }
  #endif

}

[global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
public sealed partial class AttackResponse : pb::IMessage<AttackResponse>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<AttackResponse> _parser = new pb::MessageParser<AttackResponse>(() => new AttackResponse());
  private pb::UnknownFieldSet _unknownFields;
  private int _hasBits0;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<AttackResponse> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::ServerMessagesReflection.Descriptor.MessageTypes[3]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public AttackResponse() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public AttackResponse(AttackResponse other) : this() {
    _hasBits0 = other._hasBits0;
    playerId_ = other.playerId_;
    targetId_ = other.targetId_;
    targetHpAfterAttack_ = other.targetHpAfterAttack_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public AttackResponse Clone() {
    return new AttackResponse(this);
  }

  /// <summary>Field number for the "player_id" field.</summary>
  public const int PlayerIdFieldNumber = 1;
  private readonly static string PlayerIdDefaultValue = "";

  private string playerId_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string PlayerId {
    get { return playerId_ ?? PlayerIdDefaultValue; }
    set {
      playerId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }
  /// <summary>Gets whether the "player_id" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool HasPlayerId {
    get { return playerId_ != null; }
  }
  /// <summary>Clears the value of the "player_id" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void ClearPlayerId() {
    playerId_ = null;
  }

  /// <summary>Field number for the "target_id" field.</summary>
  public const int TargetIdFieldNumber = 2;
  private readonly static string TargetIdDefaultValue = "";

  private string targetId_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string TargetId {
    get { return targetId_ ?? TargetIdDefaultValue; }
    set {
      targetId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }
  /// <summary>Gets whether the "target_id" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool HasTargetId {
    get { return targetId_ != null; }
  }
  /// <summary>Clears the value of the "target_id" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void ClearTargetId() {
    targetId_ = null;
  }

  /// <summary>Field number for the "target_hp_after_attack" field.</summary>
  public const int TargetHpAfterAttackFieldNumber = 3;
  private readonly static float TargetHpAfterAttackDefaultValue = 0F;

  private float targetHpAfterAttack_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public float TargetHpAfterAttack {
    get { if ((_hasBits0 & 1) != 0) { return targetHpAfterAttack_; } else { return TargetHpAfterAttackDefaultValue; } }
    set {
      _hasBits0 |= 1;
      targetHpAfterAttack_ = value;
    }
  }
  /// <summary>Gets whether the "target_hp_after_attack" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool HasTargetHpAfterAttack {
    get { return (_hasBits0 & 1) != 0; }
  }
  /// <summary>Clears the value of the "target_hp_after_attack" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void ClearTargetHpAfterAttack() {
    _hasBits0 &= ~1;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as AttackResponse);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(AttackResponse other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (PlayerId != other.PlayerId) return false;
    if (TargetId != other.TargetId) return false;
    if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(TargetHpAfterAttack, other.TargetHpAfterAttack)) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (HasPlayerId) hash ^= PlayerId.GetHashCode();
    if (HasTargetId) hash ^= TargetId.GetHashCode();
    if (HasTargetHpAfterAttack) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(TargetHpAfterAttack);
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (HasPlayerId) {
      output.WriteRawTag(10);
      output.WriteString(PlayerId);
    }
    if (HasTargetId) {
      output.WriteRawTag(18);
      output.WriteString(TargetId);
    }
    if (HasTargetHpAfterAttack) {
      output.WriteRawTag(29);
      output.WriteFloat(TargetHpAfterAttack);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (HasPlayerId) {
      output.WriteRawTag(10);
      output.WriteString(PlayerId);
    }
    if (HasTargetId) {
      output.WriteRawTag(18);
      output.WriteString(TargetId);
    }
    if (HasTargetHpAfterAttack) {
      output.WriteRawTag(29);
      output.WriteFloat(TargetHpAfterAttack);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (HasPlayerId) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(PlayerId);
    }
    if (HasTargetId) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(TargetId);
    }
    if (HasTargetHpAfterAttack) {
      size += 1 + 4;
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(AttackResponse other) {
    if (other == null) {
      return;
    }
    if (other.HasPlayerId) {
      PlayerId = other.PlayerId;
    }
    if (other.HasTargetId) {
      TargetId = other.TargetId;
    }
    if (other.HasTargetHpAfterAttack) {
      TargetHpAfterAttack = other.TargetHpAfterAttack;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          PlayerId = input.ReadString();
          break;
        }
        case 18: {
          TargetId = input.ReadString();
          break;
        }
        case 29: {
          TargetHpAfterAttack = input.ReadFloat();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 10: {
          PlayerId = input.ReadString();
          break;
        }
        case 18: {
          TargetId = input.ReadString();
          break;
        }
        case 29: {
          TargetHpAfterAttack = input.ReadFloat();
          break;
        }
      }
    }
  }
  #endif

}

#endregion


#endregion Designer generated code
